dataset:
  root: data/
  train_part: 0.95
  name: custom_data
  sample_rate: 22050
bpe:
  train: true
  model_path: yttm.bpe
train:
  seed: 42
  num_workers: 8
  batch_size: 16
  clip_grad_norm: 3
  epochs: 100
  optimizer:
    lr: 0.0005 # 0.0003 
    weight_decay: 0.0001 # leave default
  # from_checkpoint: checkpoints/model_26_0.7433850436343121.pth

wandb:
  project: Vietnamsese Speech Recognition
  log_interval: 20
model:
  name: _quartznet5x5_config
  vocab_size: 150
  feat_in: 64

